; Vortex 2.0 - ESP32 CYD (ESP32-2432S028)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DARDUINO_JSON
lib_deps =
    bblanchon/ArduinoJson
    bodmer/TFT_eSPI
    paulstoffregen/XPT2046_Touchscreen
