/* Vortex AI v3 FIXED - ESP32-2432S028 CYD */
#include <Arduino.h>
#include <SPI.h>
#include <SD.h>
#include <TFT_eSPI.h>
#include <XPT2046_Touchscreen.h>
#include <math.h>
#define USER_SETUP_LOADED
#define ILI9341_DRIVER
#define TFT_WIDTH 240
#define TFT_HEIGHT 320
#define TFT_MISO 12
#define TFT_MOSI 13
#define TFT_SCLK 14
#define TFT_CS 15
#define TFT_DC 2
#define TFT_RST -1
#define LOAD_GLCD
#define SPI_FREQUENCY 40000000
#define SPI_READ_FREQUENCY 20000000
#define SD_CS 5
#define TOUCH_CS 33
#define TOUCH_IRQ 36
#define TFT_BL 21
TFT_eSPI tft=TFT_eSPI(); XPT2046_Touchscreen touch(TOUCH_CS,TOUCH_IRQ);
const char* MODEL="/vortex/model.bin"; const char* TOK="/vortex/tokenizer.bin"; const char* PURPOSE="/vortex/purpose.txt"; const char* CMD="208682De";
String purpose="Help Dzavious Ojelade with tasks, learning, programming, electronics, game development, and general problem solving."; bool sdOK=false,editPurpose=false;
struct C{int vocab,dim,hidden,layers,heads,kvheads,seq;}; struct W{float*emb,*r1,*q,*k,*v,*o,*r2,*w1,*w2,*w3,*rf,*cls;}; struct S{float*x,*xb,*xb2,*hb,*hb2,*q,*k,*v,*att,*logits,*kc,*vc;}; struct M{C c{};W w{};S s{};uint8_t*blob=nullptr;bool loaded=false;}; M m; char**vocab=nullptr;
void* A(size_t n){void*p=ps_malloc(n);return p?p:malloc(n);} String rf(const char*p){if(!sdOK)return"";File f=SD.open(p);if(!f)return"";String s=f.readString();f.close();return s;}
void ui(const String&t,const String&s){tft.fillScreen(TFT_BLACK);tft.fillRect(0,0,320,40,TFT_DARKGREY);tft.setTextColor(TFT_WHITE,TFT_DARKGREY);tft.setTextSize(2);tft.setCursor(7,11);tft.print(t);tft.setTextColor(TFT_WHITE,TFT_BLACK);tft.setTextSize(1);int y=55;String line;for(size_t i=0;i<s.length()&&y<232;i++){char c=s[i];if(c=='\n'||line.length()>47){tft.setCursor(6,y);tft.print(line);y+=12;line="";if(c!='\n')line+=c;}else line+=c;}if(line.length())tft.setCursor(6,y),tft.print(line);}
void savePurpose(){if(!sdOK)return;File f=SD.open(PURPOSE,FILE_WRITE);if(f){f.print(purpose);f.close();}} void loadPurpose(){String s=rf(PURPOSE);s.trim();if(s.length())purpose=s;}
float dot(const float*a,const float*b,int n){float z=0;for(int i=0;i<n;i++)z+=a[i]*b[i];return z;} void rms(float*o,const float*x,const float*w,int n){float z=0;for(int i=0;i<n;i++)z+=x[i]*x[i];z=1/sqrtf(z/n+1e-5f);for(int i=0;i<n;i++)o[i]=x[i]*z*w[i];} void mm(float*o,const float*x,const float*w,int n,int d){for(int i=0;i<d;i++)o[i]=dot(w+(size_t)i*n,x,n);} void soft(float*x,int n){float mx=x[0],sum=0;for(int i=1;i<n;i++)if(x[i]>mx)mx=x[i];for(int i=0;i<n;i++){x[i]=expf(x[i]-mx);sum+=x[i];}for(int i=0;i<n;i++)x[i]/=sum;}
bool state(){int d=m.c.dim,h=m.c.hidden,kv=d*m.c.kvheads/m.c.heads,L=m.c.layers;m.s.x=(float*)A(d*4);m.s.xb=(float*)A(d*4);m.s.xb2=(float*)A(d*4);m.s.hb=(float*)A(h*4);m.s.hb2=(float*)A(h*4);m.s.q=(float*)A(d*4);m.s.k=(float*)A(kv*4);m.s.v=(float*)A(kv*4);m.s.att=(float*)A(m.c.heads*m.c.seq*4);m.s.logits=(float*)A(m.c.vocab*4);m.s.kc=(float*)A((size_t)L*m.c.seq*kv*4);m.s.vc=(float*)A((size_t)L*m.c.seq*kv*4);return m.s.x&&m.s.xb&&m.s.xb2&&m.s.hb&&m.s.hb2&&m.s.q&&m.s.k&&m.s.v&&m.s.att&&m.s.logits&&m.s.kc&&m.s.vc;}
bool loadModel(){if(!sdOK)return false;File f=SD.open(MODEL);if(!f)return false;size_t n=f.size();m.blob=(uint8_t*)A(n);if(!m.blob){f.close();return false;}if(f.read(m.blob,n)!=n){f.close();return false;}f.close();memcpy(&m.c,m.blob,28);if(m.c.vocab!=256||m.c.dim<=0||m.c.hidden<=0)return false;float*p=(float*)(m.blob+28);int d=m.c.dim,h=m.c.hidden,L=m.c.layers,head=d/m.c.heads,kv=d*m.c.kvheads/m.c.heads;m.w.emb=p;p+=(size_t)256*d;m.w.r1=p;p+=(size_t)L*d;m.w.q=p;p+=(size_t)L*d*d;m.w.k=p;p+=(size_t)L*d*kv;m.w.v=p;p+=(size_t)L*d*kv;m.w.o=p;p+=(size_t)L*d*d;m.w.r2=p;p+=(size_t)L*d;m.w.w1=p;p+=(size_t)L*d*h;m.w.w2=p;p+=(size_t)L*h*d;m.w.w3=p;p+=(size_t)L*d*h;m.w.rf=p;p+=d;p+=(size_t)m.c.seq*head/2;p+=(size_t)m.c.seq*head/2;m.w.cls=p;if(!state())return false;memset(m.s.kc,0,(size_t)L*m.c.seq*kv*4);memset(m.s.vc,0,(size_t)L*m.c.seq*kv*4);m.loaded=true;return true;}
bool loadTok(){if(!sdOK)return false;File f=SD.open(TOK);if(!f)return false;uint32_t max; if(f.read((uint8_t*)&max,4)!=4){f.close();return false;}vocab=(char**)A(256*sizeof(char*));if(!vocab){f.close();return false;}for(int i=0;i<256;i++){float score;uint32_t len;if(f.read((uint8_t*)&score,4)!=4||f.read((uint8_t*)&len,4)!=4){f.close();return false;}vocab[i]=(char*)A(len+1);if(!vocab[i]||f.read((uint8_t*)vocab[i],len)!=len){f.close();return false;}vocab[i][len]=0;}f.close();return true;}
float* forward(int token,int pos){int d=m.c.dim,h=m.c.hidden,L=m.c.layers,head=d/m.c.heads,kv=d*m.c.kvheads/m.c.heads,mul=m.c.heads/m.c.kvheads;memcpy(m.s.x,m.w.emb+(size_t)token*d,d*4);for(int l=0;l<L;l++){rms(m.s.xb,m.s.x,m.w.r1+(size_t)l*d,d);mm(m.s.q,m.s.xb,m.w.q+(size_t)l*d*d,d,d);mm(m.s.k,m.s.xb,m.w.k+(size_t)l*d*kv,d,kv);mm(m.s.v,m.s.xb,m.w.v+(size_t)l*d*kv,d,kv);for(int hh=0;hh<m.c.heads;hh++)for(int i=0;i<head;i+=2){float fr=1/powf(10000,(float)i/head),a=pos*fr,c=cosf(a),s=sinf(a);float*q=m.s.q+hh*head,q0=q[i],q1=q[i+1];q[i]=q0*c-q1*s;q[i+1]=q0*s+q1*c;if(hh<m.c.kvheads){float*k=m.s.k+hh*head,k0=k[i],k1=k[i+1];k[i]=k0*c-k1*s;k[i+1]=k0*s+k1*c;}}size_t off=(size_t)l*m.c.seq*kv;memcpy(m.s.kc+off+(size_t)pos*kv,m.s.k,kv*4);memcpy(m.s.vc+off+(size_t)pos*kv,m.s.v,kv*4);for(int hh=0;hh<m.c.heads;hh++){float*q=m.s.q+hh*head,*a=m.s.att+hh*m.c.seq;for(int t=0;t<=pos;t++)a[t]=dot(q,m.s.kc+off+(size_t)t*kv+(hh/mul)*head,head)/sqrtf(head);soft(a,pos+1);float*xb=m.s.xb+hh*head;memset(xb,0,head*4);for(int t=0;t<=pos;t++){float*v=m.s.vc+off+(size_t)t*kv+(hh/mul)*head;for(int i=0;i<head;i++)xb[i]+=a[t]*v[i];}}mm(m.s.xb2,m.s.x,m.w.o+(size_t)l*d*d,d,d);for(int i=0;i<d;i++)m.s.x[i]+=m.s.xb2[i];rms(m.s.xb,m.s.x,m.w.r2+(size_t)l*d,d);mm(m.s.hb,m.s.xb,m.w.w1+(size_t)l*d*h,d,h);mm(m.s.hb2,m.s.xb,m.w.w3+(size_t)l*d*h,d,h);for(int i=0;i<h;i++)m.s.hb[i]=(m.s.hb[i]/(1+expf(-m.s.hb[i])))*m.s.hb2[i];mm(m.s.xb2,m.s.hb,m.w.w2+(size_t)l*h*d,h,d);for(int i=0;i<d;i++)m.s.x[i]+=m.s.xb2[i];}rms(m.s.x,m.s.x,m.w.rf,d);mm(m.s.logits,m.s.x,m.w.cls,d,256);return m.s.logits;}
String sdKnowledge(const String&q){if(!sdOK)return"";String low=q;low.toLowerCase();String dirs[]={"/vortex/knowledge/physics","/vortex/knowledge/math","/vortex/knowledge/programming","/vortex/knowledge/esp32","/vortex/knowledge/godot","/vortex/knowledge/roblox","/vortex/knowledge/general","/vortex/memory"};String best="";for(String dir:dirs){File d=SD.open(dir);if(!d||!d.isDirectory())continue;File f=d.openNextFile();while(f){if(!f.isDirectory()){String name=f.name();if(name.endsWith(".txt")||name.endsWith(".md")){String s=f.readString();String z=s;z.toLowerCase();if(z.indexOf(low)>=0){best=s.substring(0,min(900,(int)s.length()));f.close();d.close();return best;}}}f.close();f=d.openNextFile();}d.close();}return best;}
String builtIn(String q){String l=q;l.toLowerCase();if(l.indexOf("physics")>=0||l.indexOf("newton")>=0||l.indexOf("gravity")>=0||l.indexOf("force")>=0)return"Physics: F=m*a. Momentum is p=m*v. Kinetic energy is E=1/2*m*v^2. Near Earth, g is about 9.81 m/s^2.";if(l.indexOf("math")>=0||l.indexOf("equation")>=0||l.indexOf("calculate")>=0)return"Math: give me the exact problem and I will work it step by step.";if(l.indexOf("program")>=0||l.indexOf("code")>=0||l.indexOf("debug")>=0)return"Programming: I can help with C++, Python, GDScript, C#, JavaScript and Luau.";if(l.indexOf("esp32")>=0||l.indexOf("cyd")>=0||l.indexOf("arduino")>=0)return"ESP32/CYD: ESP32-2432S028, LCD SPI MOSI 13, MISO 12, SCLK 14, CS 15, DC 2; SD CS 5; touch CS 33.";if(l.indexOf("godot")>=0||l.indexOf("gdscript")>=0)return"Godot: I can help with Godot 4 scenes, nodes, GDScript, C#, UI and 2D/3D systems.";if(l.indexOf("roblox")>=0||l.indexOf("luau")>=0)return"Roblox: I can help with Luau, RemoteEvents, UI, RPG systems and server/client architecture.";if(l.indexOf("who are you")>=0||l.indexOf("what are you")>=0)return"I am Vortex, an offline AI assistant designed to help Dzavious Ojelade.";if(l=="hi"||l=="hello"||l=="hey")return"Hello Dzavious. I'm Vortex. What are we working on?";return"";}
String answer(String q){String b=builtIn(q);if(b.length())return b;String k=sdKnowledge(q);if(k.length())return"SD knowledge:\n"+k;if(!m.loaded)return"No matching knowledge found. Add .txt or .md files under /vortex/knowledge.";int toks[64],n=min(64,(int)q.length());String prompt="User: "+q+"\nVortex:";for(int i=0;i<n;i++)toks[i]=(uint8_t)prompt[i];n=min(64,(int)prompt.length());memset(m.s.kc,0,(size_t)m.c.layers*m.c.seq*(m.c.dim*m.c.kvheads/m.c.heads)*4);memset(m.s.vc,0,(size_t)m.c.layers*m.c.seq*(m.c.dim*m.c.kvheads/m.c.heads)*4);for(int i=0;i<n-1;i++)forward(toks[i],i);int cur=toks[n-1];String out;for(int step=0;step<40&&n+step<m.c.seq;step++){float*lg=forward(cur,n+step);int best=0;for(int j=1;j<256;j++)if(lg[j]>lg[best])best=j;char c=(char)best;if(c<32&&c!='\n'&&c!='\t')break;out+=c;cur=best;}return out.length()?out:"I need more information.";}
void handle(String q){q.trim();if(!q.length())return;if(editPurpose){purpose=q;savePurpose();editPurpose=false;Serial.println("VORTEX: My purpose has been updated.");ui("PURPOSE","Updated:\n"+purpose);return;}if(q==CMD){editPurpose=true;Serial.println("VORTEX: What is my purpose?");ui("PURPOSE","What is my purpose?\nType the new purpose in Serial Monitor.");return;}String l=q;l.toLowerCase();if(l=="show purpose"||l=="what is your purpose"){Serial.println("VORTEX PURPOSE: "+purpose);ui("PURPOSE",purpose);return;}String a=answer(q);Serial.println("VORTEX: "+a);ui("VORTEX",a);}
void setup(){Serial.begin(115200);pinMode(TFT_BL,OUTPUT);digitalWrite(TFT_BL,LOW);delay(80);tft.init();tft.setRotation(1);tft.fillScreen(TFT_RED);delay(100);tft.fillScreen(TFT_GREEN);delay(100);tft.fillScreen(TFT_BLUE);delay(100);tft.fillScreen(TFT_BLACK);digitalWrite(TFT_BL,HIGH);touch.begin();touch.setRotation(1);sdOK=SD.begin(SD_CS);if(sdOK){if(!SD.exists("/vortex"))SD.mkdir("/vortex");if(!SD.exists("/vortex/knowledge"))SD.mkdir("/vortex/knowledge");loadPurpose();}bool a=loadModel(),b=a&&loadTok();ui("VORTEX AI v3","SD: "+String(sdOK?"OK":"MISSING")+"\nModel: "+String(a?"TRAINED":"NOT FOUND")+"\nTokenizer: "+String(b?"OK":"NOT FOUND")+"\nPurpose:\n"+purpose);Serial.println("Vortex AI v3 ready. Command 208682De changes purpose.");}
void loop(){if(Serial.available())handle(Serial.readStringUntil('\n'));delay(10);}
