"""
Simple converter: quantize float numpy arrays to int8 and emit a C header usable as a drop-in replacement for `quantized_model.h`.

Usage:
  python convert_model.py --w1 w1.npy --b1 b1.npy --w2 w2.npy --b2 b2.npy --out quantized_model.h

This script demonstrates per-tensor symmetric quantization.
"""
import argparse
import numpy as np

def quantize_tensor(x, symmetric=True):
    r = np.max(np.abs(x))
    if r == 0:
        scale = 1.0
    else:
        scale = r / 127.0
    q = np.round(x / scale).astype(np.int8)
    return q, scale

fmt_row = lambda arr: ','.join(str(int(x)) for x in arr)

parser = argparse.ArgumentParser()
parser.add_argument('--w1', required=True)
parser.add_argument('--b1', required=True)
parser.add_argument('--w2', required=True)
parser.add_argument('--b2', required=True)
parser.add_argument('--out', required=True)
args = parser.parse_args()

w1 = np.load(args.w1)
b1 = np.load(args.b1)
w2 = np.load(args.w2)
b2 = np.load(args.b2)

q_w1, s_w1 = quantize_tensor(w1)
q_b1, s_b1 = quantize_tensor(b1)
q_w2, s_w2 = quantize_tensor(w2)
q_b2, s_b2 = quantize_tensor(b2)

with open(args.out, 'w') as f:
    f.write('#pragma once\n\n')
    f.write('// Generated by convert_model.py\n')
    f.write(f'#define QM_INPUT_DIM {w1.shape[1]}\n')
    f.write(f'#define QM_HIDDEN_DIM {w1.shape[0]}\n')
    f.write(f'#define QM_OUTPUT_DIM {w2.shape[0]}\n\n')
    f.write('static const int8_t QM_W1[QM_HIDDEN_DIM][QM_INPUT_DIM] = {\n')
    for r in q_w1:
        f.write('  {' + fmt_row(r) + '},\n')
    f.write('};\n\n')
    f.write('static const int8_t QM_B1[QM_HIDDEN_DIM] = {' + fmt_row(q_b1) + '};\n\n')
    f.write('static const int8_t QM_W2[QM_OUTPUT_DIM][QM_HIDDEN_DIM] = {\n')
    for r in q_w2:
        f.write('  {' + fmt_row(r) + '},\n')
    f.write('};\n\n')
    f.write('static const int8_t QM_B2[QM_OUTPUT_DIM] = {' + fmt_row(q_b2) + '};\n\n')
    f.write(f'static const float QM_SCALE_W1 = {s_w1}f;\n')
    f.write(f'static const float QM_SCALE_B1 = {s_b1}f;\n')
    f.write(f'static const float QM_SCALE_W2 = {s_w2}f;\n')
    f.write(f'static const float QM_SCALE_B2 = {s_b2}f;\n')
    f.write('\n')
    f.write('// TODO: output vocab mapping if available\n')

print('Wrote', args.out)
