#include "vortex_web.h"
#include "tiny_llm.h"
#include <WiFi.h>
#include <WebServer.h>
#include <Preferences.h>
#include <HTTPClient.h>
#include <WiFiClientSecure.h>
#include <esp_system.h>

extern TinyLLM llm;
static WebServer web(80);
static Preferences pref;
static String adminHash, directorHash, directorName, purposeText, token, role, userName;
static unsigned long tokenUntil=0;
static float voiceRate=1.0f;
static const char* ELEVEN_VOICE_ID="CqoqSUD4nHOeuLYTkwJG";
static const char* ELEVEN_MODEL_ID="eleven_multilingual_v2";
static String elevenApiKey;

static String hx(const String&s){uint32_t a=2166136261u,b=0x9e3779b9u;for(size_t i=0;i<s.length();i++){a^=(uint8_t)s[i];a*=16777619u;b^=(a>>13)+(uint8_t)s[i];b*=0x85ebca6bu;}char o[25];snprintf(o,sizeof(o),"%08lx%08lx%08lx",(unsigned long)a,(unsigned long)b,(unsigned long)(a^b^0xA5A55A5Au));return o;}
static String rnd(size_t n=24){const char*c="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";String r;for(size_t i=0;i<n;i++)r+=c[esp_random()%57];return r;}
static String esc(String s){s.replace("\\","\\\\");s.replace("\"","\\\"");s.replace("\n","\\n");s.replace("\r","\\r");return s;}
static void json(int code,const String&s){web.send(code,"application/json",s);}
static bool ok(const String&need=""){return token.length()&&millis()<tokenUntil&&web.header("X-Vortex-Session")==token&&(need.length()==0||role==need);}

static const char PAGE[] PROGMEM=R"HTML(
<!doctype html><html><head><meta name=viewport content="width=device-width,initial-scale=1"><title>Vortex AI</title><style>
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 55% 40%,#182353,#070a18 58%);color:#eef3ff;font:14px Segoe UI,Arial}.app{min-height:100vh;display:grid;grid-template-columns:235px 1fr 285px}.side,.right{background:#0a0f27ee;border-color:#252d59;padding:18px}.side{border-right:1px solid}.right{border-left:1px solid}.brand{font-size:23px;font-weight:800;margin-bottom:20px}.brand b,.cyan{color:#14d8ff}.nav button,.control{display:block;width:100%;padding:12px;margin:4px 0;border:0;border-radius:11px;background:transparent;color:#aab5dd;text-align:left}.nav button:hover,.nav .active,.control{background:#151f49;color:white}.box,.metric{background:#101735;border:1px solid #252f60;border-radius:14px;padding:14px;margin-top:14px}.box small{color:#7f8cb8}.main{padding:20px 28px}.top{display:flex;justify-content:space-between}.online{color:#55e4b0}.layout{display:grid;grid-template-columns:180px 1fr;gap:18px;margin-top:25px}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:10px}.metric label{display:block;font-size:10px;color:#14d8ff;text-transform:uppercase}.bar{height:6px;background:#29315b;border-radius:9px;margin-top:10px}.bar i{display:block;height:100%;background:linear-gradient(90deg,#14d8ff,#8b5cf6);border-radius:9px}.center{text-align:center}.orb{width:280px;height:280px;border-radius:50%;margin:5px auto;background:radial-gradient(circle,#14265d,#080e27 62%,#050815);border:2px solid #14d8ff99;box-shadow:0 0 45px #14d8ff44,inset 0 0 50px #8b5cf633;position:relative}.orb:after{content:'';position:absolute;left:-5%;right:-5%;top:50%;height:2px;background:linear-gradient(90deg,transparent,#14d8ff,#c05cff,#14d8ff,transparent);box-shadow:0 0 16px #14d8ff;animation:p 1.2s infinite alternate}@keyframes p{to{opacity:.35;transform:scaleX(.7)}}#listen{font-size:24px;margin:10px}.chat{display:flex;gap:8px;background:#0c1331;border:1px solid #293466;border-radius:15px;padding:10px;margin:18px auto 0;max-width:700px}.chat input{flex:1;background:transparent;border:0;outline:0;color:#fff}.btn{border:0;border-radius:10px;padding:11px 14px;background:#1769ed;color:white}.mic{background:#172455}.modal{position:fixed;inset:0;background:#000b;display:flex;align-items:center;justify-content:center;z-index:5}.modal.hide{display:none}.login{width:360px;background:#101735;border:1px solid #354174;border-radius:18px;padding:24px}.login input{width:100%;padding:12px;margin:6px 0;background:#090f27;border:1px solid #2a3565;color:white;border-radius:10px}.tabs{display:flex;gap:6px}.tabs button{flex:1;padding:10px;border:0;border-radius:9px;background:#17204b;color:#dbe3ff}.hide{display:none!important}.muted{color:#8b98c4}@media(max-width:1000px){.app{grid-template-columns:200px 1fr}.right{display:none}}@media(max-width:680px){.app{display:block}.side{display:none}.main{padding:14px}.layout{grid-template-columns:1fr}.orb{width:220px;height:220px}}
</style></head><body>
<div id=login class="modal"><div class=login><h2>VORTEX <span class=cyan>AI</span> <small>V4</small></h2><div class=tabs><button onclick="mode='admin'">Admin</button><button onclick="mode='director'">Director</button><button onclick="mode='guest';fields()">Guest</button></div><div id=fields><input id=u placeholder=Username><input id=p type=password placeholder=Password><button class=btn onclick=login()>Sign in</button></div><div id=gfields class=hide><input id=gn placeholder="Your name"><button class=btn onclick=guest()>Enter as Guest</button></div><p id=msg class=muted></p></div></div>
<div class=app><aside class=side><div class=brand><b>VORTEX</b> AI <small>V4</small></div><div class=nav><button class=active>⌂ Dashboard</button><button>◌ Conversations</button><button id=cmd>✦ Commands</button><button>◇ Knowledge</button><button>♡ Memory</button><button>▣ Media</button><button id=users>♙ Users</button><button id=settings>⚙ Settings</button><button>◷ Logs</button></div><div class=box><small>ACTIVE ROLE</small><div id=roleText>Guest</div><small id=nameText>Guest User</small></div><div class=box><small>SYSTEM</small><p>Model <span class=online>Online</span></p><p>Voice <span class=online>ElevenLabs</span></p><p>Voice ID <span class=online>CqoqSUD4nHOeuLYTkwJG</span></p><p>SD <span class=online>128 GB</span></p><p>Wi-Fi <span class=online>AP</span></p></div></aside>
<main class=main><div class=top><b>AI Assistance › <span class=cyan>Vortex</span> <span class=online>● Online</span></b><span>☼　♧　🎙</span></div><div class=layout><div class=metrics><div class=metric><label>Knowledge</label><b>Ready</b><div class=bar><i style="width:82%"></i></div></div><div class=metric><label>Conversation</label><b>Ready</b><div class=bar><i style="width:76%"></i></div></div><div class=metric><label>ESP32</label><b>Ready</b><div class=bar><i style="width:91%"></i></div></div><div class=metric><label>Storage</label><b>128 GB</b><div class=bar><i style="width:69%"></i></div></div><div class=metric><label>Memory</label><b>Active</b><div class=bar><i style="width:64%"></i></div></div><div class=metric><label>Voice</label><b>Ready</b><div class=bar><i style="width:88%"></i></div></div></div><div class=center><div class=orb></div><div class=cyan id=greet>How can I help you?</div><div id=listen>Ready</div><div style="font-size:34px">🎙</div><button class="btn mic" onclick=listenNow()>Talk to Vortex</button><div class=chat><input id=q placeholder="Type a message or speak..."><button class="btn mic" onclick=listenNow()>🎙</button><button class=btn onclick=chat()>➤</button></div></div></div></main>
<aside class=right><div class=box><b>VORTEX RESPONSE</b><p id=answer class=cyan>Ready for a conversation.</p></div><div class=box><b>CONTROL CENTER</b><div id=controls><button class=control onclick=purpose()>⚙ System Purpose</button><button class=control onclick=command()>⌘ Run Command</button><button class=control onclick=usersMenu()>♙ User Management</button><button class=control onclick=commandMenu()>✦ Command Center</button><button class=control onclick=voiceMenu()>🔊 ElevenLabs Voice</button><button class=control onclick=settingsMenu()>⚙ System Settings</button></div></div><div class=box><b>ACTIVE USER</b><p id=active>Guest</p><button class=btn onclick=location.reload()>Sign out</button></div></aside></div>
<script>
let mode='admin',tok='',R='guest';function fields(){document.getElementById('fields').classList.add('hide');document.getElementById('gfields').classList.remove('hide')}async function login(){let r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'role='+mode+'&username='+encodeURIComponent(u.value)+'&password='+encodeURIComponent(p.value)}),d=await r.json();if(!r.ok){msg.textContent=d.error;return}tok=d.token;start(d)}async function guest(){let r=await fetch('/api/guest',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'name='+encodeURIComponent(gn.value)}),d=await r.json();tok=d.token;start(d)}async function start(d){R=d.role;document.getElementById('login').classList.add('hide');roleText.textContent=R.toUpperCase();nameText.textContent=d.name||R;active.textContent=d.name||R;greet.textContent='How can I help you today, '+(d.name||'there').split(' ')[0]+'?';document.getElementById('controls').classList.toggle('hide',R==='guest');settings.classList.toggle('hide',R==='guest');if(R==='director'&&!d.name){let n=prompt('Welcome, Director. Please enter your name:');if(n){await fetch('/api/director/setup',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'name='+encodeURIComponent(n)});nameText.textContent=n;active.textContent=n;greet.textContent='How can I help you today, '+n.split(' ')[0]+'?'}}}
async function chat(){let x=q.value.trim();if(!x)return;q.value='';listen.textContent='Thinking...';let r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'message='+encodeURIComponent(x)}),d=await r.json();answer.textContent=d.answer||d.error;listen.textContent='Ready';if(d.answer)speak(d.answer)}
async function speak(t){try{let r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'text='+encodeURIComponent(t)});if(r.ok){let b=await r.blob(),u=URL.createObjectURL(b),a=new Audio(u);a.onended=()=>URL.revokeObjectURL(u);await a.play();return}}catch(e){}if(window.speechSynthesis){let s=new SpeechSynthesisUtterance(t);s.rate=1;speechSynthesis.cancel();speechSynthesis.speak(s)}}
function listenNow(){let S=window.SpeechRecognition||window.webkitSpeechRecognition;if(!S)return alert('Use Chrome or Edge for browser voice input.');let r=new S();r.lang='en-US';r.onstart=()=>listen.textContent='Listening...';r.onresult=e=>{q.value=e.results[0][0].transcript;chat()};r.onerror=e=>listen.textContent='Voice error';r.onend=()=>{if(listen.textContent==='Listening...')listen.textContent='Ready'};r.start()}
async function purpose(){if(R!=='admin')return alert('Admin only');let x=prompt('New Vortex purpose:');if(!x)return;let r=await fetch('/api/admin/purpose',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'purpose='+encodeURIComponent(x)});alert((await r.json()).message||'Updated')}
async function command(){if(R!=='admin')return alert('Admin only');let x=prompt('Command (status or reboot):','status');if(!x)return;let r=await fetch('/api/admin/command',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'command='+encodeURIComponent(x)});alert((await r.json()).result||'Denied')}
async function usersMenu(){if(R!=='admin')return alert('Admin only');let x=prompt('Set Director password (leave blank to cancel):');if(!x)return;let r=await fetch('/api/admin/director',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'password='+encodeURIComponent(x)});alert((await r.json()).message||'Updated')}
async function commandMenu(){if(R!=='admin')return alert('Admin only');let x=prompt('Add a safe command name (registry only):');if(!x)return;let r=await fetch('/api/admin/add-command',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'name='+encodeURIComponent(x)});alert((await r.json()).message||'Saved')}
async function voiceMenu(){if(R!=='admin')return alert('Admin only');let x=prompt('ElevenLabs API key. It will be stored locally on the ESP32 and never committed to GitHub:');if(!x)return;let r=await fetch('/api/admin/elevenlabs',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'key='+encodeURIComponent(x)});alert((await r.json()).message||'Saved')}
async function settingsMenu(){if(R==='guest')return alert('Guests cannot change settings');let x=prompt('Voice speed 0.5 to 2.0:','1.0');if(!x)return;let r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Vortex-Session':tok},body:'voiceRate='+encodeURIComponent(x)});alert((await r.json()).message||'Saved')}
</script></body></html>
)HTML";

static void root(){web.send_P(200,"text/html",PAGE);}
static void login(){String r=web.arg("role"),u=web.arg("username"),p=web.arg("password");if(r=="admin"&&u.equalsIgnoreCase("dezavious")&&hx(p)==adminHash)role="admin",userName="Dezavious Ojelade";else if(r=="director"&&u.equalsIgnoreCase("director")&&hx(p)==directorHash)role="director",userName=directorName;else{return json(401,"{\"error\":\"Invalid login\"}");}token=rnd();tokenUntil=millis()+86400000UL;json(200,"{\"token\":\""+token+"\",\"role\":\""+role+"\",\"name\":\""+esc(userName)+"\"}");}
static void guest(){role="guest";userName=web.arg("name");if(!userName.length())userName="Guest User";token=rnd();tokenUntil=millis()+43200000UL;json(200,"{\"token\":\""+token+"\",\"role\":\"guest\",\"name\":\""+esc(userName)+"\"}");}
static void chat(){if(!ok())return json(401,"{\"error\":\"Session expired\"}");String q=web.arg("message");if(q=="208682De"&&role=="admin")return json(200,"{\"answer\":\"Purpose mode is open. Use System Purpose in the Admin Control Center.\"}");String a=llm.generate(q,64);if(!a.length())a="I am Vortex. My local model did not return an answer.";json(200,"{\"answer\":\""+esc(a)+"\"}");}
static void setupDirector(){if(!ok("director"))return json(403,"{\"error\":\"Director only\"}");String n=web.arg("name");if(n.length()<2)return json(400,"{\"error\":\"Invalid name\"}");directorName=n;userName=n;pref.putString("dname",n);json(200,"{\"message\":\"Director name saved.\"}");}
static void purpose(){if(!ok("admin"))return json(403,"{\"error\":\"Admin only\"}");purposeText=web.arg("purpose");if(!purposeText.length())return json(400,"{\"error\":\"Empty purpose\"}");pref.putString("purpose",purposeText);json(200,"{\"message\":\"Vortex purpose updated.\"}");}
static void command(){if(!ok("admin"))return json(403,"{\"error\":\"Admin only\"}");String c=web.arg("command");c.toLowerCase();if(c=="status")return json(200,"{\"result\":\"Vortex online at "+WiFi.softAPIP().toString()+".\"}");if(c=="reboot"){json(200,"{\"result\":\"Rebooting...\"}");delay(200);ESP.restart();}json(403,"{\"error\":\"Command not registered.\"}");}
static void directorPassword(){if(!ok("admin"))return json(403,"{\"error\":\"Admin only\"}");String p=web.arg("password");if(p.length()<6)return json(400,"{\"error\":\"Use at least 6 characters\"}");directorHash=hx(p);pref.putString("director",directorHash);json(200,"{\"message\":\"Director password updated.\"}");}
static void addCommand(){if(!ok("admin"))return json(403,"{\"error\":\"Admin only\"}");String n=web.arg("name");if(n.length()<1)return json(400,"{\"error\":\"Empty command\"}");String list=pref.getString("cmds","");if(list.length())list+=';';list+=n;pref.putString("cmds",list);json(200,"{\"message\":\"Command added to the Vortex command registry.\"}");}
static void settings(){if(!ok("admin")&&!ok("director"))return json(403,"{\"error\":\"Permission denied\"}");voiceRate=web.arg("voiceRate").toFloat();if(voiceRate<0.5f||voiceRate>2.0f)voiceRate=1.0f;pref.putFloat("rate",voiceRate);json(200,"{\"message\":\"Settings saved.\"}");}
static void elevenlabsKey(){if(!ok("admin"))return json(403,"{\"error\":\"Admin only\"}");String k=web.arg("key");if(k.length()<10)return json(400,"{\"error\":\"Invalid ElevenLabs API key\"}");elevenApiKey=k;pref.putString("eleven_key",elevenApiKey);json(200,"{\"message\":\"ElevenLabs voice configured for Vortex.\"}");}
static void elevenlabsTTS(){if(!ok())return json(401,"{\"error\":\"Session expired\"}");if(!elevenApiKey.length())return json(503,"{\"error\":\"ElevenLabs is not configured. Use Admin > ElevenLabs Voice.\"}");String text=web.arg("text");text.trim();if(!text.length())return json(400,"{\"error\":\"Empty text\"}");if(text.length()>1800)text=text.substring(0,1800);WiFiClientSecure client;client.setInsecure();HTTPClient http;String url=String("https://api.elevenlabs.io/v1/text-to-speech/")+ELEVEN_VOICE_ID+"?output_format=mp3_22050_32";if(!http.begin(client,url))return json(502,"{\"error\":\"Could not connect to ElevenLabs\"}");http.addHeader("xi-api-key",elevenApiKey);http.addHeader("Content-Type","application/json");String body=String("{\"text\":\"")+esc(text)+String("\",\"model_id\":\"")+ELEVEN_MODEL_ID+String("\",\"voice_settings\":{\"stability\":0.5,\"similarity_boost\":0.8,\"speed\":")+String(voiceRate,2)+String("}}");int code=http.POST(body);if(code!=200){String err=http.getString();http.end();return json(code>0?code:502,String("{\"error\":\"ElevenLabs TTS failed: ")+esc(err.substring(0,180))+"\"}");}int len=http.getSize();web.sendHeader("Cache-Control","no-store");web.setContentLength(len);web.send(200,"audio/mpeg","");WiFiClient* stream=http.getStreamPtr();uint8_t buf[1024];while(http.connected()&&(len>0||len==-1)){size_t avail=stream->available();if(avail){int n=stream->readBytes(buf,min(avail,(size_t)sizeof(buf)));web.sendContent((const char*)buf,n);if(len>0)len-=n;}else{delay(1);}}http.end();}

void vortexWebBegin(){pref.begin("vortex-auth",false);adminHash=pref.getString("admin","");directorHash=pref.getString("director",hx("director"));directorName=pref.getString("dname","");purposeText=pref.getString("purpose","Help Dezavious Ojelade with tasks, programming, learning, engineering, and everyday work.");voiceRate=pref.getFloat("rate",1.0f);elevenApiKey=pref.getString("eleven_key","");if(!adminHash.length()){String initial="Vortex-"+String((uint32_t)(ESP.getEfuseMac()&0xFFFFFFFF),HEX);adminHash=hx(initial);pref.putString("admin",adminHash);Serial.println("[VORTEX] FIRST RUN ADMIN: dezavious");Serial.println("[VORTEX] FIRST RUN PASSWORD: "+initial);}WiFi.mode(WIFI_AP);WiFi.softAP("Vortex-AI","VortexAI123");const char* hdrs[]={"X-Vortex-Session"};web.collectHeaders(hdrs,1);web.on("/",HTTP_GET,root);web.on("/api/login",HTTP_POST,login);web.on("/api/guest",HTTP_POST,guest);web.on("/api/chat",HTTP_POST,chat);web.on("/api/tts",HTTP_POST,elevenlabsTTS);web.on("/api/director/setup",HTTP_POST,setupDirector);web.on("/api/admin/purpose",HTTP_POST,purpose);web.on("/api/admin/command",HTTP_POST,command);web.on("/api/admin/director",HTTP_POST,directorPassword);web.on("/api/admin/add-command",HTTP_POST,addCommand);web.on("/api/admin/elevenlabs",HTTP_POST,elevenlabsKey);web.on("/api/settings",HTTP_POST,settings);web.begin();Serial.print("[VORTEX] Open http://");Serial.println(WiFi.softAPIP());}
void vortexWebLoop(){web.handleClient();}
